# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='trips', to='login_app.User'),
        ),
    ]
