# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('poke_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.AddField(
            model_name='poke',
            name='poked',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poked', to='login_app.User'),
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poker', to='login_app.User'),
        ),
    ]
