# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0002_auto_20161118_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poked', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_poker', to='login_app.User'),
        ),
    ]
